services:                                         # Defines the services/containers we want to run
  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./app:/app
      - ./app/data:/app/data
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/NY_taxi 
    ports:
      - "8888:8888" 
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root 

  ingest_data:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./app:/app
      - ./app/data:/app/data
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/NY_taxi 
    command: /bin/bash -c "python pipeline_yellow.py && python pipeline_green.py &&  python zones.py"

  postgres:                                      
    image: postgres:16                            
    environment:                                  
      - POSTGRES_USER=user                        
      - POSTGRES_PASSWORD=password                
      - POSTGRES_DB=NY_taxi                       
    ports:
      - "5433:5432"                               
    volumes:
      - postgres_data:/var/lib/postgresql/data    

  pgadmin:
    image: dpage/pgadmin4                         
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com     
      - PGADMIN_DEFAULT_PASSWORD=admin            
      - PGADMIN_SERVER_JSON_FILE=/pgadmin4/servers.json
    ports:
      - "8080:80"                                 
    depends_on:
      - postgres                                  
    volumes:
      - ./servers.json:/pgadmin4/servers.json

volumes:
  postgres_data:                                  